name: drowsiness_detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - ipython=8.14.0
  - mlflow=2.4.1
  - pip=23.1.2
  - pywin32=305
  - py-opencv=4.7.0
  - pip:
      - wandb==0.15.4
      - pygame==2.5.0
      - ultralytics==8.0.124
      - Pillow==10.0.0